/**
 * @description       : 
 * @author            : Prabhu Sajjanam
 * @group             : 
 * @last modified on  : 08-07-2020
 * @last modified by  : Prabhu Sajjanam
 * Modifications Log 
 * Ver   Date         Author            Modification
 * 1.0   08-07-2020   Prabhu Sajjanam   Initial Version
**/

public class c1{

list<Account> acts=[select name,phone,type,industry,fax from account];

public list<account> getacts()

{return acts;}


//this is my new line
//one more line
}